import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es-MX">
      <body>
        <div className="min-h-screen bg-gray-900 text-gray-300 flex flex-col items-center">
          {children}
        </div>
      </body>
    </html>
  )
}
